import Vue from 'vue'
import Vuex from 'vuex'
import createPersistedState from "vuex-persistedstate";

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    bugConnexion: false,
    showNavbar: true,
    MenuSarezide: false,
    LoginZone: false,
    users: {
      nom: '',
      prenom: '',
      email: '',
      contact: '',
      adresse: '',
      photo: '',
      pays: '',
      role: '',
      statut: '',
      genre: '',
      email_recept: '',
      id: null,
    },
    biens: {
      libelle: '',
      type_item: '',
      nm_prop_item: '',
      pren_prop_item: '',
      cnt_prop_item: '',
      eml_prop_item: '',
      adresse_item: '',
      ville_item: '',
      commune_item: '',
      quartier_item: '',
      zone_item: '',
      contact_item: '',
      apt_item: '',
      nb_apt_item: '',
      nb_chb_item: '1',
      nb_sal_item: '0',
      nb_sb_item: '1',
      tarif_jour: '',
      tarif_journee: '',
      tarif_nuit: '',
      nb_jour_reduction: '',
      tarif_jour_reduction: '',
      description: '',
      eqpm_parking: 0,
      eqpm_petit_dej: 0,
      eqpm_langue1: 'Langue 1',
      eqpm_langue2: 'Langue 2',
      eqpm_langue3: 'Langue 3',
      eqpm_evenement: 0,
      event_anniversaire: 0,
      event_mariage: 0,
      event_bapteme: 0,
      event_tournage: 0,
      event_festivite: 0,
      eqpm_climatisation: 0,
      eqpm_piscine_pb: 0,
      eqpm_piscine_pv: 0,
      eqpm_seche_linge: 0,
      eqpm_armoire: 0,
      eqpm_moquette: 0,
      eqpm_dressing: 0,
      eqpm_ventilateur: 0,
      eqpm_chauffage: 0,
      eqpm_fer_repasse: 0,
      eqpm_mt_repasse: 0,
      eqpm_moustiquaire: 0,
      eqpm_canape_chambre: 0,
      eqpm_balcon: 0,
      eqpm_lave_linge: 0,
      eqpm_bureau: 0,
      eqpm_bar: 0,
      eqpm_baignoire: 0,
      eqpm_peignoire: 0,
      eqpm_jacuzzi: 0,
      eqpm_sauna: 0,
      eqpm_seche_cheveu: 0,
      eqpm_papier_toilette: 0,
      eqpm_ordinateur: 0,
      eqpm_lecteur_dvd: 0,
      eqpm_telephone: 0,
      eqpm_internet: 0,
      eqpm_fax: 0,
      eqpm_chaine_sat: 0,
      eqpm_tv: 0,
      eqpm_table_mange: 0,
      eqpm_ustensile: 0,
      eqpm_machine_cafe: 0,
      eqpm_barbecue: 0,
      eqpm_four: 0,
      eqpm_lave_vaiselle: 0,
      eqpm_micro_ondes: 0,
      eqpm_kitchenette: 0,
      eqpm_bouilloir_electrique: 0,
      eqpm_refrigerateur: 0,
      eqpm_vue_ville: 0,
      eqpm_vue_piscine: 0,
      eqpm_vue_riviere: 0,
      eqpm_vue_mer: 0,
      eqpm_jardin: 0,
      eqpm_terasse: 0,
      eqpm_vue_lac: 0,
      eqpm_jeux_puzzles: 0,
      eqpm_livres: 0,
      agent_securite: 0,
      video_surveillance: 0,
      capteur_presence: 0,
      antivol: 0,
      barbele: 0,
      localisation_longitude: '',
      localisation_latitude: '',
      image1: '',
      image2: '',
      image3: '',
      image4: '',
      image5: '',
      image6: '',
      image7: '',
      image8: '',
      user: '',
      date_item: '',
      autorisation: 'oo',
      statut: '',
      autoriseur: '',
      chb_1_nb_lit: '',
      chb_1_lit: '',
      chb_1_nb_personne: '',
      chb_2_nb_lit: '',
      chb_2_lit: '',
      chb_2_nb_personne: '',
      chb_3_nb_lit: '',
      chb_3_lit: '',
      chb_3_nb_personne: '',
      chb_4_nb_lit: '',
      chb_4_lit: '',
      chb_4_nb_personne: '',
      chb_5_nb_lit: '',
      chb_5_lit: '',
      chb_5_nb_personne: '',
      horaire_jour_entre: '',
      horaire_jour_sorti: '',
      tarif_parking: 0,
      peti_dej_1: '',
      peti_dej_2: '',
      peti_dej_3: '',
      },
      biensm: {
        id_item: 0,
        libelle: '',
        type_item: '',
        nm_prop_item: '',
        pren_prop_item: '',
        cnt_prop_item: '',
        eml_prop_item: '',
        adresse_item: '',
        ville_item: '',
        commune_item: '',
        quartier_item: '',
        zone_item: '',
        contact_item: '',
        apt_item: '',
        nb_apt_item: '',
        nb_chb_item: '1',
        nb_sal_item: '0',
        nb_sb_item: '1',
        tarif_jour: '',
        tarif_journee: '',
        tarif_nuit: '',
        nb_jour_reduction: '',
        tarif_jour_reduction: '',
        description: '',
        eqpm_parking: 0,
        eqpm_petit_dej: 0,
        eqpm_langue1: 'Langue 1',
        eqpm_langue2: 'Langue 2',
        eqpm_langue3: 'Langue 3',
        eqpm_evenement: 0,
        event_anniversaire: 0,
        event_mariage: 0,
        event_bapteme: 0,
        event_tournage: 0,
        event_festivite: 0,
        eqpm_climatisation: 0,
        eqpm_piscine_pb: 0,
        eqpm_piscine_pv: 0,
        eqpm_seche_linge: 0,
        eqpm_armoire: 0,
        eqpm_moquette: 0,
        eqpm_dressing: 0,
        eqpm_ventilateur: 0,
        eqpm_chauffage: 0,
        eqpm_fer_repasse: 0,
        eqpm_mt_repasse: 0,
        eqpm_moustiquaire: 0,
        eqpm_canape_chambre: 0,
        eqpm_balcon: 0,
        eqpm_lave_linge: 0,
        eqpm_bureau: 0,
        eqpm_bar: 0,
        eqpm_baignoire: 0,
        eqpm_peignoire: 0,
        eqpm_jacuzzi: 0,
        eqpm_sauna: 0,
        eqpm_seche_cheveu: 0,
        eqpm_papier_toilette: 0,
        eqpm_ordinateur: 0,
        eqpm_lecteur_dvd: 0,
        eqpm_telephone: 0,
        eqpm_internet: 0,
        eqpm_fax: 0,
        eqpm_chaine_sat: 0,
        eqpm_tv: 0,
        eqpm_table_mange: 0,
        eqpm_ustensile: 0,
        eqpm_machine_cafe: 0,
        eqpm_barbecue: 0,
        eqpm_four: 0,
        eqpm_lave_vaiselle: 0,
        eqpm_micro_ondes: 0,
        eqpm_kitchenette: 0,
        eqpm_bouilloir_electrique: 0,
        eqpm_refrigerateur: 0,
        eqpm_vue_ville: 0,
        eqpm_vue_piscine: 0,
        eqpm_vue_riviere: 0,
        eqpm_vue_mer: 0,
        eqpm_jardin: 0,
        eqpm_terasse: 0,
        eqpm_vue_lac: 0,
        eqpm_jeux_puzzles: 0,
        eqpm_livres: 0,
        agent_securite: 0,
        video_surveillance: 0,
        capteur_presence: 0,
        antivol: 0,
        barbele: 0,
        localisation_longitude: '',
        localisation_latitude: '',
        image1: '',
        image2: '',
        image3: '',
        image4: '',
        image5: '',
        image6: '',
        image7: '',
        image8: '',
        user: '',
        date_item: '',
        autorisation: 'oo',
        statut: '',
        autoriseur: '',
        chb_1_nb_lit: '',
        chb_1_lit: '',
        chb_1_nb_personne: '',
        chb_2_nb_lit: '',
        chb_2_lit: '',
        chb_2_nb_personne: '',
        chb_3_nb_lit: '',
        chb_3_lit: '',
        chb_3_nb_personne: '',
        chb_4_nb_lit: '',
        chb_4_lit: '',
        chb_4_nb_personne: '',
        chb_5_nb_lit: '',
        chb_5_lit: '',
        chb_5_nb_personne: '',
        horaire_jour_entre: '',
        horaire_jour_sorti: '',
        tarif_parking: 0,
        peti_dej_1: '',
        peti_dej_2: '',
        peti_dej_3: '',
      },
      biensdetails: {
        id_item: 0,
        libelle: '',
        type_item: '',
        nm_prop_item: '',
        pren_prop_item: '',
        cnt_prop_item: '',
        eml_prop_item: '',
        adresse_item: '',
        ville_item: '',
        commune_item: '',
        quartier_item: '',
        zone_item: '',
        contact_item: '',
        apt_item: '',
        nb_apt_item: '',
        nb_chb_item: '1',
        nb_sal_item: '0',
        nb_sb_item: '1',
        tarif_jour: '',
        tarif_journee: '',
        tarif_nuit: '',
        nb_jour_reduction: '',
        tarif_jour_reduction: '',
        description: '',
        eqpm_parking: 0,
        eqpm_petit_dej: 0,
        eqpm_langue1: 'Langue 1',
        eqpm_langue2: 'Langue 2',
        eqpm_langue3: 'Langue 3',
        eqpm_evenement: 0,
        event_anniversaire: 0,
        event_mariage: 0,
        event_bapteme: 0,
        event_tournage: 0,
        event_festivite: 0,
        eqpm_climatisation: 0,
        eqpm_piscine_pb: 0,
        eqpm_piscine_pv: 0,
        eqpm_seche_linge: 0,
        eqpm_armoire: 0,
        eqpm_moquette: 0,
        eqpm_dressing: 0,
        eqpm_ventilateur: 0,
        eqpm_chauffage: 0,
        eqpm_fer_repasse: 0,
        eqpm_mt_repasse: 0,
        eqpm_moustiquaire: 0,
        eqpm_canape_chambre: 0,
        eqpm_balcon: 0,
        eqpm_lave_linge: 0,
        eqpm_bureau: 0,
        eqpm_bar: 0,
        eqpm_baignoire: 0,
        eqpm_peignoire: 0,
        eqpm_jacuzzi: 0,
        eqpm_sauna: 0,
        eqpm_seche_cheveu: 0,
        eqpm_papier_toilette: 0,
        eqpm_ordinateur: 0,
        eqpm_lecteur_dvd: 0,
        eqpm_telephone: 0,
        eqpm_internet: 0,
        eqpm_fax: 0,
        eqpm_chaine_sat: 0,
        eqpm_tv: 0,
        eqpm_table_mange: 0,
        eqpm_ustensile: 0,
        eqpm_machine_cafe: 0,
        eqpm_barbecue: 0,
        eqpm_four: 0,
        eqpm_lave_vaiselle: 0,
        eqpm_micro_ondes: 0,
        eqpm_kitchenette: 0,
        eqpm_bouilloir_electrique: 0,
        eqpm_refrigerateur: 0,
        eqpm_vue_ville: 0,
        eqpm_vue_piscine: 0,
        eqpm_vue_riviere: 0,
        eqpm_vue_mer: 0,
        eqpm_jardin: 0,
        eqpm_terasse: 0,
        eqpm_vue_lac: 0,
        eqpm_jeux_puzzles: 0,
        eqpm_livres: 0,
        agent_securite: 0,
        video_surveillance: 0,
        capteur_presence: 0,
        antivol: 0,
        barbele: 0,
        localisation_longitude: '',
        localisation_latitude: '',
        image1: '',
        image2: '',
        image3: '',
        image4: '',
        image5: '',
        image6: '',
        image7: '',
        image8: '',
        user: '',
        date_item: '',
        autorisation: 'oo',
        statut: '',
        autoriseur: '',
        chb_1_nb_lit: '',
        chb_1_lit: '',
        chb_1_nb_personne: '',
        chb_2_nb_lit: '',
        chb_2_lit: '',
        chb_2_nb_personne: '',
        chb_3_nb_lit: '',
        chb_3_lit: '',
        chb_3_nb_personne: '',
        chb_4_nb_lit: '',
        chb_4_lit: '',
        chb_4_nb_personne: '',
        chb_5_nb_lit: '',
        chb_5_lit: '',
        chb_5_nb_personne: '',
        horaire_jour_entre: '',
        horaire_jour_sorti: '',
        tarif_parking: 0,
        peti_dej_1: '',
        peti_dej_2: '',
        peti_dej_3: '',
        },
    results: [],
    resultsr: {
      total_rows: 0,
      total_pages: 0,
      current_page: 1,
    },
    searchByHome: false,
    agent: 0,
    admin: 0,
    client: 0,
  },
  getters: {
  },
  mutations: {
    Resultats: (state, data) => {
      state.results = data;
      state.searchByHome = false;
    },
    ProfilPhoto: (state, data) => {
      state.users.photo = data;
    },
    BugCorrige: (state, data) => {
      state.bugConnexion = data;
    },
    NavbarShow: (state, data) => {
      state.showNavbar = data;
    },
    LoginShow: (state, data) => {
      state.LoginZone = data;
    },
    Resultatsr: (state, data) => {
      state.resultsr.total_rows = data.total_rows;
      state.resultsr.total_pages = data.total_pages;
      state.resultsr.current_page = data.current_page;
    },
    ResultatByHome: (state, data) => {
      state.results = data;
      state.searchByHome = true;
    },
    ConnexionAgent: (state, data) => {
      state.users.nom = data.nom;
      state.users.prenom = data.prenom;
      state.users.email = data.email;
      state.users.contact = data.contact;
      state.users.adresse = data.adresse;
      state.users.photo = data.photo;
      state.users.pays = data.pays;
      state.users.role = data.role;
      state.users.statut = data.statut;
      state.users.genre = data.genre;
      state.users.id = data.id;
      state.users.email_recept = data.email_recept;
      state.agent = 1;
      state.client = 0;
    },
    ConnexionAgent2: (state, data) => {
      state.users.nom = data.nom;
      state.users.prenom = data.prenom;
      state.users.contact = data.contact;
      state.users.adresse = data.adresse;
      state.users.pays = data.pays;
      state.users.genre = data.genre;
    },
    ConnexionClient: (state, data) => {
      state.users.nom = data.nom;
      state.users.prenom = data.prenom;
      state.users.email = data.email;
      state.users.contact = data.contact;
      state.users.adresse = data.adresse;
      state.users.photo = data.photo;
      state.users.pays = data.pays;
      state.users.role = data.role;
      state.users.statut = data.statut;
      state.users.genre = data.genre;
      state.users.id = data.id_utilisateur;
      state.users.email_recept = data.email_recept;
      state.client = 1;
      state.agent = 0;
    },
    Deconnexion: (state, data) => {
      state.users.nom = data.nom;
      state.users.prenom = data.prenom;
      state.users.email = data.email;
      state.users.contact = data.contact;
      state.users.adresse = data.adresse;
      state.users.photo = data.photo;
      state.users.pays = data.pays;
      state.users.role = data.role;
      state.users.statut = data.statut;
      state.users.genre = data.genre;
      state.users.id = data.id_utilisateur;
      state.client = 0;
      state.agent = 0;
      state.admin = 0;
    },
    updateMenuState: (state, data) => {
      state.MenuSarezide = data;
    },
    BiensAjout: (state, data) => {
      state.biens = {
        libelle: data.libelle,
        type_item: data.type_item,
        nm_prop_item: data.nm_prop_item,
        pren_prop_item: data.pren_prop_item,
        cnt_prop_item: data.cnt_prop_item,
        eml_prop_item: data.eml_prop_item,
        adresse_item: data.adresse_item,
        ville_item: data.ville_item,
        commune_item: data.commune_item,
        quartier_item: data.quartier_item,
        zone_item: data.zone_item,
        contact_item: data.contact_item,
        apt_item: data.apt_item,
        nb_apt_item: data.nb_apt_item,
        nb_chb_item: data.nb_chb_item,
        nb_sal_item: data.nb_sal_item,
        nb_sb_item: data.nb_sb_item,
        tarif_jour: data.tarif_jour,
        tarif_journee: data.tarif_journee,
        tarif_nuit: data.tarif_nuit,
        nb_jour_reduction: data.nb_jour_reduction,
        tarif_jour_reduction: data.tarif_jour_reduction,
        description: data.description,
        eqpm_parking: data.eqpm_parking,
        eqpm_petit_dej: data.eqpm_petit_dej,
        eqpm_langue1: data.eqpm_langue1,
        eqpm_langue2: data.eqpm_langue2,
        eqpm_langue3: data.eqpm_langue3,
        eqpm_evenement: data.eqpm_evenement,
        event_anniversaire: data.event_anniversaire,
        event_mariage: data.event_mariage,
        event_bapteme: data.event_bapteme,
        event_tournage: data.event_tournage,
        event_festivite: data.event_festivite,
        eqpm_climatisation: data.eqpm_climatisation,
        eqpm_piscine_pb: data.eqpm_piscine_pb,
        eqpm_piscine_pv: data.eqpm_piscine_pv,
        eqpm_seche_linge: data.eqpm_seche_linge,
        eqpm_armoire: data.eqpm_armoire,
        eqpm_moquette: data.eqpm_moquette,
        eqpm_dressing: data.eqpm_dressing,
        eqpm_ventilateur: data.eqpm_ventilateur,
        eqpm_chauffage: data.eqpm_chauffage,
        eqpm_fer_repasse: data.eqpm_fer_repasse,
        eqpm_mt_repasse: data.eqpm_mt_repasse,
        eqpm_moustiquaire: data.eqpm_moustiquaire,
        eqpm_canape_chambre: data.eqpm_canape_chambre,
        eqpm_balcon: data.eqpm_balcon,
        eqpm_lave_linge: data.eqpm_lave_linge,
        eqpm_bureau: data.eqpm_bureau,
        eqpm_bar: data.eqpm_bar,
        eqpm_baignoire: data.eqpm_baignoire,
        eqpm_peignoire: data.eqpm_peignoire,
        eqpm_jacuzzi: data.eqpm_jacuzzi,
        eqpm_sauna: data.eqpm_sauna,
        eqpm_seche_cheveu: data.eqpm_seche_cheveu,
        eqpm_papier_toilette: data.eqpm_papier_toilette,
        eqpm_ordinateur: data.eqpm_ordinateur,
        eqpm_lecteur_dvd: data.eqpm_lecteur_dvd,
        eqpm_telephone: data.eqpm_telephone,
        eqpm_internet: data.eqpm_internet,
        eqpm_fax: data.eqpm_fax,
        eqpm_chaine_sat: data.eqpm_chaine_sat,
        eqpm_tv: data.eqpm_tv,
        eqpm_table_mange: data.eqpm_table_mange,
        eqpm_ustensile: data.eqpm_ustensile,
        eqpm_machine_cafe: data.eqpm_machine_cafe,
        eqpm_barbecue: data.eqpm_barbecue,
        eqpm_four: data.eqpm_four,
        eqpm_lave_vaiselle: data.eqpm_lave_vaiselle,
        eqpm_micro_ondes: data.eqpm_micro_ondes,
        eqpm_kitchenette: data.eqpm_kitchenette,
        eqpm_bouilloir_electrique: data.eqpm_bouilloir_electrique,
        eqpm_refrigerateur: data.eqpm_refrigerateur,
        eqpm_vue_ville: data.eqpm_vue_ville,
        eqpm_vue_piscine: data.eqpm_vue_piscine,
        eqpm_vue_riviere: data.eqpm_vue_riviere,
        eqpm_vue_mer: data.eqpm_vue_mer,
        eqpm_jardin: data.eqpm_jardin,
        eqpm_terasse: data.eqpm_terasse,
        eqpm_vue_lac: data.eqpm_vue_lac,
        eqpm_jeux_puzzles: data.eqpm_jeux_puzzles,
        eqpm_livres: data.eqpm_livres,
        agent_securite: data.agent_securite,
        video_surveillance: data.video_surveillance,
        capteur_presence: data.capteur_presence,
        antivol: data.antivol,
        barbele: data.barbele,
        localisation_longitude: data.localisation_longitude,
        localisation_latitude: data.localisation_latitude,
        image1: data.image1,
        image2: data.image2,
        image3: data.image3,
        image4: data.image4,
        image5: data.image5,
        image6: data.image6,
        image7: data.image7,
        image8: data.image8,
        user: data.user,
        date_item: data.date_item,
        autorisation: data.autorisation,
        statut: data.statut,
        autoriseur: data.autoriseur,
        chb_1_nb_lit: data.chb_1_nb_lit,
        chb_1_lit: data.chb_1_lit,
        chb_1_nb_personne: data.chb_1_nb_personne,
        chb_2_nb_lit: data.chb_2_nb_lit,
        chb_2_lit: data.chb_2_lit,
        chb_2_nb_personne: data.chb_2_nb_personne,
        chb_3_nb_lit: data.chb_3_nb_lit,
        chb_3_lit: data.chb_3_lit,
        chb_3_nb_personne: data.chb_3_nb_personne,
        chb_4_nb_lit: data.chb_4_nb_lit,
        chb_4_lit: data.chb_4_lit,
        chb_4_nb_personne: data.chb_4_nb_personne,
        chb_5_nb_lit: data.chb_5_nb_lit,
        chb_5_lit: data.chb_5_lit,
        chb_5_nb_personne: data.chb_5_nb_personne,
        horaire_jour_entre: data.horaire_jour_entre,
        horaire_jour_sorti: data.horaire_jour_sorti,
        tarif_parking: data.tarif_parking,
        peti_dej_1: data.peti_dej_1,
        peti_dej_2: data.peti_dej_2,
        peti_dej_3: data.peti_dej_3
      };
    },
    BiensModif: (state, data) => {
      state.biensm = {
        libelle: data.libelle,
        type_item: data.type_item,
        nm_prop_item: data.nm_prop_item,
        pren_prop_item: data.pren_prop_item,
        cnt_prop_item: data.cnt_prop_item,
        eml_prop_item: data.eml_prop_item,
        adresse_item: data.adresse_item,
        ville_item: data.ville_item,
        commune_item: data.commune_item,
        quartier_item: data.quartier_item,
        zone_item: data.zone_item,
        contact_item: data.contact_item,
        apt_item: data.apt_item,
        nb_apt_item: data.nb_apt_item,
        nb_chb_item: data.nb_chb_item,
        nb_sal_item: data.nb_sal_item,
        nb_sb_item: data.nb_sb_item,
        tarif_jour: data.tarif_jour,
        tarif_journee: data.tarif_journee,
        tarif_nuit: data.tarif_nuit,
        nb_jour_reduction: data.nb_jour_reduction,
        tarif_jour_reduction: data.tarif_jour_reduction,
        description: data.description,
        eqpm_parking: data.eqpm_parking,
        eqpm_petit_dej: data.eqpm_petit_dej,
        eqpm_langue1: data.eqpm_langue1,
        eqpm_langue2: data.eqpm_langue2,
        eqpm_langue3: data.eqpm_langue3,
        eqpm_evenement: data.eqpm_evenement,
        event_anniversaire: data.event_anniversaire,
        event_mariage: data.event_mariage,
        event_bapteme: data.event_bapteme,
        event_tournage: data.event_tournage,
        event_festivite: data.event_festivite,
        eqpm_climatisation: data.eqpm_climatisation,
        eqpm_piscine_pb: data.eqpm_piscine_pb,
        eqpm_piscine_pv: data.eqpm_piscine_pv,
        eqpm_seche_linge: data.eqpm_seche_linge,
        eqpm_armoire: data.eqpm_armoire,
        eqpm_moquette: data.eqpm_moquette,
        eqpm_dressing: data.eqpm_dressing,
        eqpm_ventilateur: data.eqpm_ventilateur,
        eqpm_chauffage: data.eqpm_chauffage,
        eqpm_fer_repasse: data.eqpm_fer_repasse,
        eqpm_mt_repasse: data.eqpm_mt_repasse,
        eqpm_moustiquaire: data.eqpm_moustiquaire,
        eqpm_canape_chambre: data.eqpm_canape_chambre,
        eqpm_balcon: data.eqpm_balcon,
        eqpm_lave_linge: data.eqpm_lave_linge,
        eqpm_bureau: data.eqpm_bureau,
        eqpm_bar: data.eqpm_bar,
        eqpm_baignoire: data.eqpm_baignoire,
        eqpm_peignoire: data.eqpm_peignoire,
        eqpm_jacuzzi: data.eqpm_jacuzzi,
        eqpm_sauna: data.eqpm_sauna,
        eqpm_seche_cheveu: data.eqpm_seche_cheveu,
        eqpm_papier_toilette: data.eqpm_papier_toilette,
        eqpm_ordinateur: data.eqpm_ordinateur,
        eqpm_lecteur_dvd: data.eqpm_lecteur_dvd,
        eqpm_telephone: data.eqpm_telephone,
        eqpm_internet: data.eqpm_internet,
        eqpm_fax: data.eqpm_fax,
        eqpm_chaine_sat: data.eqpm_chaine_sat,
        eqpm_tv: data.eqpm_tv,
        eqpm_table_mange: data.eqpm_table_mange,
        eqpm_ustensile: data.eqpm_ustensile,
        eqpm_machine_cafe: data.eqpm_machine_cafe,
        eqpm_barbecue: data.eqpm_barbecue,
        eqpm_four: data.eqpm_four,
        eqpm_lave_vaiselle: data.eqpm_lave_vaiselle,
        eqpm_micro_ondes: data.eqpm_micro_ondes,
        eqpm_kitchenette: data.eqpm_kitchenette,
        eqpm_bouilloir_electrique: data.eqpm_bouilloir_electrique,
        eqpm_refrigerateur: data.eqpm_refrigerateur,
        eqpm_vue_ville: data.eqpm_vue_ville,
        eqpm_vue_piscine: data.eqpm_vue_piscine,
        eqpm_vue_riviere: data.eqpm_vue_riviere,
        eqpm_vue_mer: data.eqpm_vue_mer,
        eqpm_jardin: data.eqpm_jardin,
        eqpm_terasse: data.eqpm_terasse,
        eqpm_vue_lac: data.eqpm_vue_lac,
        eqpm_jeux_puzzles: data.eqpm_jeux_puzzles,
        eqpm_livres: data.eqpm_livres,
        agent_securite: data.agent_securite,
        video_surveillance: data.video_surveillance,
        capteur_presence: data.capteur_presence,
        antivol: data.antivol,
        barbele: data.barbele,
        localisation_longitude: data.localisation_longitude,
        localisation_latitude: data.localisation_latitude,
        image1: data.image1,
        image2: data.image2,
        image3: data.image3,
        image4: data.image4,
        image5: data.image5,
        image6: data.image6,
        image7: data.image7,
        image8: data.image8,
        user: data.user,
        date_item: data.date_item,
        autorisation: data.autorisation,
        statut: data.statut,
        autoriseur: data.autoriseur,
        chb_1_nb_lit: data.chb_1_nb_lit,
        chb_1_lit: data.chb_1_lit,
        chb_1_nb_personne: data.chb_1_nb_personne,
        chb_2_nb_lit: data.chb_2_nb_lit,
        chb_2_lit: data.chb_2_lit,
        chb_2_nb_personne: data.chb_2_nb_personne,
        chb_3_nb_lit: data.chb_3_nb_lit,
        chb_3_lit: data.chb_3_lit,
        chb_3_nb_personne: data.chb_3_nb_personne,
        chb_4_nb_lit: data.chb_4_nb_lit,
        chb_4_lit: data.chb_4_lit,
        chb_4_nb_personne: data.chb_4_nb_personne,
        chb_5_nb_lit: data.chb_5_nb_lit,
        chb_5_lit: data.chb_5_lit,
        chb_5_nb_personne: data.chb_5_nb_personne,
        horaire_jour_entre: data.horaire_jour_entre,
        horaire_jour_sorti: data.horaire_jour_sorti,
        tarif_parking: data.tarif_parking,
        peti_dej_1: data.peti_dej_1,
        peti_dej_2: data.peti_dej_2,
        peti_dej_3: data.peti_dej_3,
        id_item: data.id_item
      };
    },
    BiensDetail: (state, data) => {
      state.biensdetails = {
        libelle: data.libelle,
        type_item: data.type_item,
        nm_prop_item: data.nm_prop_item,
        pren_prop_item: data.pren_prop_item,
        cnt_prop_item: data.cnt_prop_item,
        eml_prop_item: data.eml_prop_item,
        adresse_item: data.adresse_item,
        ville_item: data.ville_item,
        commune_item: data.commune_item,
        quartier_item: data.quartier_item,
        zone_item: data.zone_item,
        contact_item: data.contact_item,
        apt_item: data.apt_item,
        nb_apt_item: data.nb_apt_item,
        nb_chb_item: data.nb_chb_item,
        nb_sal_item: data.nb_sal_item,
        nb_sb_item: data.nb_sb_item,
        tarif_jour: data.tarif_jour,
        tarif_journee: data.tarif_journee,
        tarif_nuit: data.tarif_nuit,
        nb_jour_reduction: data.nb_jour_reduction,
        tarif_jour_reduction: data.tarif_jour_reduction,
        description: data.description,
        eqpm_parking: data.eqpm_parking,
        eqpm_petit_dej: data.eqpm_petit_dej,
        eqpm_langue1: data.eqpm_langue1,
        eqpm_langue2: data.eqpm_langue2,
        eqpm_langue3: data.eqpm_langue3,
        eqpm_evenement: data.eqpm_evenement,
        event_anniversaire: data.event_anniversaire,
        event_mariage: data.event_mariage,
        event_bapteme: data.event_bapteme,
        event_tournage: data.event_tournage,
        event_festivite: data.event_festivite,
        eqpm_climatisation: data.eqpm_climatisation,
        eqpm_piscine_pb: data.eqpm_piscine_pb,
        eqpm_piscine_pv: data.eqpm_piscine_pv,
        eqpm_seche_linge: data.eqpm_seche_linge,
        eqpm_armoire: data.eqpm_armoire,
        eqpm_moquette: data.eqpm_moquette,
        eqpm_dressing: data.eqpm_dressing,
        eqpm_ventilateur: data.eqpm_ventilateur,
        eqpm_chauffage: data.eqpm_chauffage,
        eqpm_fer_repasse: data.eqpm_fer_repasse,
        eqpm_mt_repasse: data.eqpm_mt_repasse,
        eqpm_moustiquaire: data.eqpm_moustiquaire,
        eqpm_canape_chambre: data.eqpm_canape_chambre,
        eqpm_balcon: data.eqpm_balcon,
        eqpm_lave_linge: data.eqpm_lave_linge,
        eqpm_bureau: data.eqpm_bureau,
        eqpm_bar: data.eqpm_bar,
        eqpm_baignoire: data.eqpm_baignoire,
        eqpm_peignoire: data.eqpm_peignoire,
        eqpm_jacuzzi: data.eqpm_jacuzzi,
        eqpm_sauna: data.eqpm_sauna,
        eqpm_seche_cheveu: data.eqpm_seche_cheveu,
        eqpm_papier_toilette: data.eqpm_papier_toilette,
        eqpm_ordinateur: data.eqpm_ordinateur,
        eqpm_lecteur_dvd: data.eqpm_lecteur_dvd,
        eqpm_telephone: data.eqpm_telephone,
        eqpm_internet: data.eqpm_internet,
        eqpm_fax: data.eqpm_fax,
        eqpm_chaine_sat: data.eqpm_chaine_sat,
        eqpm_tv: data.eqpm_tv,
        eqpm_table_mange: data.eqpm_table_mange,
        eqpm_ustensile: data.eqpm_ustensile,
        eqpm_machine_cafe: data.eqpm_machine_cafe,
        eqpm_barbecue: data.eqpm_barbecue,
        eqpm_four: data.eqpm_four,
        eqpm_lave_vaiselle: data.eqpm_lave_vaiselle,
        eqpm_micro_ondes: data.eqpm_micro_ondes,
        eqpm_kitchenette: data.eqpm_kitchenette,
        eqpm_bouilloir_electrique: data.eqpm_bouilloir_electrique,
        eqpm_refrigerateur: data.eqpm_refrigerateur,
        eqpm_vue_ville: data.eqpm_vue_ville,
        eqpm_vue_piscine: data.eqpm_vue_piscine,
        eqpm_vue_riviere: data.eqpm_vue_riviere,
        eqpm_vue_mer: data.eqpm_vue_mer,
        eqpm_jardin: data.eqpm_jardin,
        eqpm_terasse: data.eqpm_terasse,
        eqpm_vue_lac: data.eqpm_vue_lac,
        eqpm_jeux_puzzles: data.eqpm_jeux_puzzles,
        eqpm_livres: data.eqpm_livres,
        agent_securite: data.agent_securite,
        video_surveillance: data.video_surveillance,
        capteur_presence: data.capteur_presence,
        antivol: data.antivol,
        barbele: data.barbele,
        localisation_longitude: data.localisation_longitude,
        localisation_latitude: data.localisation_latitude,
        image1: data.image1,
        image2: data.image2,
        image3: data.image3,
        image4: data.image4,
        image5: data.image5,
        image6: data.image6,
        image7: data.image7,
        image8: data.image8,
        user: data.user,
        date_item: data.date_item,
        autorisation: data.autorisation,
        statut: data.statut,
        autoriseur: data.autoriseur,
        chb_1_nb_lit: data.chb_1_nb_lit,
        chb_1_lit: data.chb_1_lit,
        chb_1_nb_personne: data.chb_1_nb_personne,
        chb_2_nb_lit: data.chb_2_nb_lit,
        chb_2_lit: data.chb_2_lit,
        chb_2_nb_personne: data.chb_2_nb_personne,
        chb_3_nb_lit: data.chb_3_nb_lit,
        chb_3_lit: data.chb_3_lit,
        chb_3_nb_personne: data.chb_3_nb_personne,
        chb_4_nb_lit: data.chb_4_nb_lit,
        chb_4_lit: data.chb_4_lit,
        chb_4_nb_personne: data.chb_4_nb_personne,
        chb_5_nb_lit: data.chb_5_nb_lit,
        chb_5_lit: data.chb_5_lit,
        chb_5_nb_personne: data.chb_5_nb_personne,
        horaire_jour_entre: data.horaire_jour_entre,
        horaire_jour_sorti: data.horaire_jour_sorti,
        tarif_parking: data.tarif_parking,
        peti_dej_1: data.peti_dej_1,
        peti_dej_2: data.peti_dej_2,
        peti_dej_3: data.peti_dej_3,
        id_item: data.id_item
      };
    },
  },
  actions: {
  },
  modules: {
  },
  plugins: [createPersistedState()]
})
